In [57]:
# Review of yesterday:

# We can store lists into variables
primes = [2,3,5,7,11,13]

# We can print it
print("The complete list",primes)
for prime in primes:
    print("a prime",prime)
print("")

# We can also use the range and len functions to get an index
for i in range(0,len(primes)):
    print("Prime number",i,"is",primes[i])
print("")

# We can also write a function:
def add_elements_of_list_smaller_than_10(input_list):
    result = 0
    for element in input_list:
        if element < 10:
            result = result + element
        else:
            print(element,"is larger than 10 and does not get added")
    return result

# Let us call it and print the result
sum_of_primes_smaller_10 = add_elements_of_list_smaller_than_10(primes)
print("")
print("The sum of all primes < 10 is",sum_of_primes_smaller_10)

The complete list [2, 3, 5, 7, 11, 13]
a prime 2
a prime 3
a prime 5
a prime 7
a prime 11
a prime 13

Prime number 0 is 2
Prime number 1 is 3
Prime number 2 is 5
Prime number 3 is 7
Prime number 4 is 11
Prime number 5 is 13

11 is larger than 10 and does not get added
13 is larger than 10 and does not get added

The sum of all primes < 10 is 17


In [7]:
# Having now understood some basic concepts of python we want
# to use build-in methods and packages to make these tasks easier
# For this we shall introduce numpy and matplotlib, starting with numpy

# In python we can load packages using the 'import' keyword
import numpy

In [12]:
# We can acess functions and elements of this package with the . operator
print( numpy.pi )
print( numpy.sqrt(9) )

3.141592653589793
3.0


In [15]:
# To make typing faster it is common to use abbreviations for the libraries, we do this with the as statement
import numpy as np

# Now we can just type, i.e. refer to numpy by using np
print( np.pi )
print( np.sqrt(9) )

3.141592653589793
3.0


In [22]:
# To work with data in numpy, we usually use np.array() objects, they are very similar to lists
a_list = primes
an_array = np.array(primes)

for prime in a_list:
    print("a prime",prime)
print("")
print("works the same for the numpy array")
print("")
for prime in an_array:
    print("a prime",prime)

a prime 2
a prime 3
a prime 5
a prime 7
a prime 11
a prime 13

works the same for the numpy array

a prime 2
a prime 3
a prime 5
a prime 7
a prime 11
a prime 13


In [51]:
# We can load the csv data with the loadtxt function from the numpy library
# This function takes a number of arguments, we can specify which we are setting with the 'name=' argument
# The others are set to default values

data = np.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

# Let us analyze the data we have loaded
print(data)
print(type(data))

# The numpy.ndarray class has built-in function to get the content type and size
# Unlike a list, a numpy array only ever contains one type of data
print(data.dtype)
print(data.shape)

# Let us unpack data.shape
dimensions = data.shape
print(dimensions)
n_rows = dimensions[0]
n_cols = dimensions[1]
print("number of rows",n_rows)
print("number of columns",n_cols)


[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
<class 'numpy.ndarray'>
float64
(60, 40)
(60, 40)
number of rows 60
number of columns 40


In [31]:
# We can access the numpy array's data in the same way we would access a list,
# Here we also introduce the idea of 2D data,
# Therefore we need a pair of indices seperated by a comma
print('first row in data:', data[0])
print('first element of first row in data:', data[0][0])

print('first element of first row in data in a more compact way:', data[0, 0])

first row in data: [ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]
first element of first row in data: 0.0
first element of first row in data in a more compact way: 0.0


In [53]:
# Maybe we don't want to print a line but a column, we could do
n_rows = data.shape[0]
for ii in range(0,n_rows):
    print(data[ii,4])
# printing the content of the "fourth" column

1.0
2.0
3.0
4.0
3.0
2.0
4.0
3.0
1.0
1.0
4.0
3.0
4.0
1.0
1.0
1.0
2.0
2.0
2.0
1.0
1.0
2.0
4.0
1.0
2.0
3.0
4.0
1.0
3.0
4.0
3.0
3.0
2.0
3.0
4.0
1.0
2.0
3.0
2.0
1.0
2.0
3.0
4.0
1.0
3.0
4.0
4.0
1.0
2.0
3.0
1.0
3.0
4.0
1.0
1.0
2.0
2.0
4.0
4.0
3.0


In [55]:
# But there is an easier way:
print(data[:,4])

[1. 2. 3. 4. 3. 2. 4. 3. 1. 1. 4. 3. 4. 1. 1. 1. 2. 2. 2. 1. 1. 2. 4. 1.
 2. 3. 4. 1. 3. 4. 3. 3. 2. 3. 4. 1. 2. 3. 2. 1. 2. 3. 4. 1. 3. 4. 4. 1.
 2. 3. 1. 3. 4. 1. 1. 2. 2. 4. 4. 3.]


In [ ]:
# But we want to introduce a new concept: slicing (also works on lists)
# Here the slice '0:4' means start at 0 and go up to - not including - 4
print(data[0:4, 0:10])

# We can ommit the upper or lower bound, that will mean start/beginning
# If we use just ':' that means all elements
small = data[:3, 36:]
print('small is:')
print(small)

# We can get one row of the data with '[0,:]'
print(small[0,:])

# Or alternatively we can get one column of the data with '[:,0]'
print(small[:,0])

In [ ]:
# Remember that strings share access concepts with lists and arrays? We can also slice strings
# Task: Given a string get the last element 
test_string = 'carpentry'

# Task Write a function which removes the first and last element of a string (using slicing)
def middle_part(input_string):
    print(input_string[1:-1])
    return input_string[1:-1]

# Task: Write a function which adds all elements of a numpy array (element-wise)
def add_rows(input_array):
    result = 0
    for row in input_array:
        for element in row:
            result = result + element
    return result

def add_rows_adv(input_array):
    return np.sum(input_array)

middle_part(test_string)
print(add_rows(data))
print(add_rows_adv(data))

In [35]:
# Numpy has many functions to analyze arrays for example we can compute mean values
print("Mean",np.mean(data))

# We can also compute maxima, minima and standard deviations of the dataset
# Note that we can assign multiple values in one line with a comma seperation on both sides
maxval, minval, stdval = np.max(data), np.min(data), np.std(data)

print('maximum inflammation:', maxval)
print('minimum inflammation:', minval)
print('standard deviation:', stdval)

Mean 6.14875
maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


In [39]:
# If ever in need of an explanation of how to use a function consult 'help(function)' or 'help(package)'
help(print)

help(np.mean)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.

Help on function mean in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an

In [ ]:
# We can now extend our repertoir of functions to include the most common numpy functions:

# numpy.arange() is the extension of the range() function to non-integer numbers
# It however returns a numpy.ndarray not a list
print(numpy.arange(5,8,2))

#? print(range(0.5,4.8,0.3))
print(numpy.arange(0.5,4.8,0.5))

# The stop float is NOT included in the array 
print(numpy.arange(0.5,5.0,0.5))
print(numpy.arange(0.5,5.1,0.5))

print(type(numpy.arange(0,4,2)))

# numpy.linspace instead provides N evenly spaced numbers in a given intervall
print(numpy.linspace(1,2,10))
print(len(numpy.linspace(1,2,10)))

In [ ]:
# Task: Write a function which computes the mean of all natural numbers
# between two given integers, Hint: This can be done without a for loop using numpy
def mean_between(a,b):
    return numpy.mean(numpy.arange(a+1,b,1))

print(mean_between(2345, 6723))

In [ ]:
# Task: Write a function that adds two arrays of equal length elementwise
# and returns a numpy array

def array_add(a,b):
    result = []
    for i in range(len(a)):
        result.append(a[i]+b[i])
    return numpy.array(result)

a = numpy.linspace(2,4,10)
b = numpy.linspace(1,5,10)

print(array_add(a,b))
print(array_add(a,b) == a+b)

# Talk about numpy array addition and multiplication 

In [ ]:
# If there is time left
# numpy.savetxt()
# numpy.zeros/ones
# higher dimensional arrays
# .dot(), .T

In [47]:
# Summary

# Packages are imported like so, the as keyword allows us to pick an alias that we want, some are THE convention
import numpy as np

# Data often has at least a two-dimensional shape is is nicely represented with a 2d numpy array
# e.g. inflammation of the wound for each patient tracked and for each day

# We can easily load .csv files into a numpy array
data = np.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

# We can get the data in a row (for a single patient)
print("Data for patient 0",data[0])
print("")
# Or for a single day:
print("Data on day 0",data[:,0])
print("")
# Or for a specific patient at a specific day
print("Data for patient 5 on day 4",data[5,4])
print("")

# We can use numpy functions to compute statistical quantities
print("Mean of all data",np.mean(data))
for row in data:
    print("Mean inflammation for single patient",np.mean(row))

print(data.shape)
print(data.shape[1])
for column_index in range(0,data.shape[1]):
    data_on_a_day = data[:,column_index]
    print("Mean inflammation for day",column_index,":",np.mean(data_on_a_day))
    
# These lists are tedious to look at if we want to identify trends, so after the break we will learn how to plot such data

Data for patient 0 [ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]

Data on day 0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Data for patient 5 on day 4 2.0

Mean of all data 6.14875
Mean inflammation for single patient 5.45
Mean inflammation for single patient 5.425
Mean inflammation for single patient 6.1
Mean inflammation for single patient 5.9
Mean inflammation for single patient 5.55
Mean inflammation for single patient 6.225
Mean inflammation for single patient 5.975
Mean inflammation for single patient 6.65
Mean inflammation for single patient 6.625
Mean inflammation for single patient 6.525
Mean inflammation for single patient 6.775
Mean inflammation for single patient 5.8
Mean inflammation for single patient 6.225
Mean infl

In [54]:
#test